name: Compress
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install rar
      run: sudo apt-get install rar -y

    - name: Compress to File
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        rar a -m5 -r -s "Source_code_${TAG_NAME}.rar" ./SD_card_root/
        
    - name: Create or Update GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          "Source_code_${TAG_NAME}.rar"
          "boot_payload.bin"
        tag_name: "${GITHUB_REF##*/}"
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
