name: Compress
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Compress to File
      run: |
        sudo apt-get install rar -y
        rar a -m5 -r -s "StarDustCFW.rar" ./SD_card_root/

    - name: Update Release
      run: | 
        gh release upload ${{github.event.release.tag_name}} StarDustCFW.rar
        echo gh release upload ${{github.event.release.tag_name}} ./SD_card_root/boot_payload.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
