name: Compress
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install rar
      run: sudo apt-get install rar -y

    - name: Compress to File
      run: |
        echo rar a -m5 -r -s "Source_code.rar" ./SD_card_root/
        ls -a
        
    - name: Update release
      run: | 
        echo gh release upload ${github.ref_name}} Source_code.rar
        gh release upload ${github.ref_name}} ./SD_card_root/boot_payload.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
