name: Compress
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install rar
      run: sudo apt-get install rar -y

    - name: Compress to File
      run: |
        rar a -m5 -r -s "Source_code.rar" ./SD_card_root/
        ls -a
        
    - name: Create or Update GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      body: TODO
      with:
        files: |
          Source_code.rar
          ./SD_card_root/boot_payload.bin
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
